Load dataframe:

In [20]:
import os
import pandas as pd

In [31]:
filename = os.path.join(os.getcwd(), "hurdat2_sample.csv")
df = pd.read_csv(filename)

In [32]:
df.head(10)

,Unnamed: 0,Year,Time,Storm Name/Record Identifier,Number of Entries/Status,Latitude,Longitude,Maximum Sustained Wind,Minimum Pressure,34-knot Wind Radii NE,...,34-knot Wind Radii SW,34-knot Wind Radii NW,50-knot Wind Radii NE,50-knot Wind Radii SE,50-knot Wind Radii SW,50-knot Wind Radii NW,64-knot Wind Radii NE,64-knot Wind Radii SE,64-knot Wind Radii SW,64-knot Wind Radii NW
0,0,AL011851,UNNAMED,14,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1851-06-25,0000,,HU,28.0N,94.8W,80.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
2,2,1851-06-25,0600,,HU,28.0N,95.4W,80.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
3,3,1851-06-25,1200,,HU,28.0N,96.0W,80.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
4,4,1851-06-25,1800,,HU,28.1N,96.5W,80.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
5,5,1851-06-25,2100,L,HU,28.2N,96.8W,80.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
6,6,1851-06-26,0000,,HU,28.2N,97.0W,70.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
7,7,1851-06-26,0600,,TS,28.3N,97.6W,60.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
8,8,1851-06-26,1200,,TS,28.4N,98.3W,60.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
9,9,1851-06-26,1800,,TS,28.6N,98.9W,50.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0

In [33]:
df.columns

Index(['Unnamed: 0', 'Year', 'Time', 'Storm Name/Record Identifier',
       'Number of Entries/Status', 'Latitude', 'Longitude',
       'Maximum Sustained Wind', 'Minimum Pressure', '34-knot Wind Radii NE',
       '34-knot Wind Radii SE', '34-knot Wind Radii SW',
       '34-knot Wind Radii NW', '50-knot Wind Radii NE',
       '50-knot Wind Radii SE', '50-knot Wind Radii SW',
       '50-knot Wind Radii NW', '64-knot Wind Radii NE',
       '64-knot Wind Radii SE', '64-knot Wind Radii SW',
       '64-knot Wind Radii NW'],
      dtype='object')

In [34]:
df.rename(columns={"Unnamed: 0": "Name", "Storm Name/Record Identifier": "Record Identifier", "Number of Entries/Status": "Status of System"}, inplace=True)
df.head(10)

,Name,Year,Time,Record Identifier,Status of System,Latitude,Longitude,Maximum Sustained Wind,Minimum Pressure,34-knot Wind Radii NE,...,34-knot Wind Radii SW,34-knot Wind Radii NW,50-knot Wind Radii NE,50-knot Wind Radii SE,50-knot Wind Radii SW,50-knot Wind Radii NW,64-knot Wind Radii NE,64-knot Wind Radii SE,64-knot Wind Radii SW,64-knot Wind Radii NW
0,0,AL011851,UNNAMED,14,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1851-06-25,0000,,HU,28.0N,94.8W,80.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
2,2,1851-06-25,0600,,HU,28.0N,95.4W,80.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
3,3,1851-06-25,1200,,HU,28.0N,96.0W,80.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
4,4,1851-06-25,1800,,HU,28.1N,96.5W,80.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
5,5,1851-06-25,2100,L,HU,28.2N,96.8W,80.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
6,6,1851-06-26,0000,,HU,28.2N,97.0W,70.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
7,7,1851-06-26,0600,,TS,28.3N,97.6W,60.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
8,8,1851-06-26,1200,,TS,28.4N,98.3W,60.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
9,9,1851-06-26,1800,,TS,28.6N,98.9W,50.0,-999.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0

In [35]:
df.dtypes

Name                        int64
Year                       object
Time                       object
Record Identifier          object
Status of System           object
Latitude                   object
Longitude                  object
Maximum Sustained Wind    float64
Minimum Pressure          float64
34-knot Wind Radii NE     float64
34-knot Wind Radii SE     float64
34-knot Wind Radii SW     float64
34-knot Wind Radii NW     float64
50-knot Wind Radii NE     float64
50-knot Wind Radii SE     float64
50-knot Wind Radii SW     float64
50-knot Wind Radii NW     float64
64-knot Wind Radii NE     float64
64-knot Wind Radii SE     float64
64-knot Wind Radii SW     float64
64-knot Wind Radii NW     float64
dtype: object

In [36]:
df.insert(1, "Num Entries", df[df["Record Identifier"].astype(str).str.isdigit()]["Record Identifier"])
df

,Name,Num Entries,Year,Time,Record Identifier,Status of System,Latitude,Longitude,Maximum Sustained Wind,Minimum Pressure,...,34-knot Wind Radii SW,34-knot Wind Radii NW,50-knot Wind Radii NE,50-knot Wind Radii SE,50-knot Wind Radii SW,50-knot Wind Radii NW,64-knot Wind Radii NE,64-knot Wind Radii SE,64-knot Wind Radii SW,64-knot Wind Radii NW
0,0,14,AL011851,UNNAMED,14,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,1851-06-25,0000,,HU,28.0N,94.8W,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
2,2,NaN,1851-06-25,0600,,HU,28.0N,95.4W,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
3,3,NaN,1851-06-25,1200,,HU,28.0N,96.0W,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
4,4,NaN,1851-06-25,1800,,HU,28.1N,96.5W,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56717,56717,NaN,10/23/2023,1800,,TD,11.5N,83.2W,25.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56718,56718,NaN,10/24/2023,0000,,TD,12.2N,83.4W,25.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56719,56719,NaN,10/24/2023,0130,L,TD,12.4N,83.5W,25.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56720,56720,NaN,10/24/2023,0600,,TD,13.0N,83.8W,25.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56721,56721,NaN,10/24/2023,1200,,LO,13.5N,84.4W,20.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
df["Name"] = df.loc[df["Year"].str.startswith("AL")]["Time"]
df

,Name,Num Entries,Year,Time,Record Identifier,Status of System,Latitude,Longitude,Maximum Sustained Wind,Minimum Pressure,...,34-knot Wind Radii SW,34-knot Wind Radii NW,50-knot Wind Radii NE,50-knot Wind Radii SE,50-knot Wind Radii SW,50-knot Wind Radii NW,64-knot Wind Radii NE,64-knot Wind Radii SE,64-knot Wind Radii SW,64-knot Wind Radii NW
0,UNNAMED,14,AL011851,UNNAMED,14,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,1851-06-25,0000,,HU,28.0N,94.8W,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
2,NaN,NaN,1851-06-25,0600,,HU,28.0N,95.4W,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
3,NaN,NaN,1851-06-25,1200,,HU,28.0N,96.0W,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
4,NaN,NaN,1851-06-25,1800,,HU,28.1N,96.5W,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56717,NaN,NaN,10/23/2023,1800,,TD,11.5N,83.2W,25.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56718,NaN,NaN,10/24/2023,0000,,TD,12.2N,83.4W,25.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56719,NaN,NaN,10/24/2023,0130,L,TD,12.4N,83.5W,25.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56720,NaN,NaN,10/24/2023,0600,,TD,13.0N,83.8W,25.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56721,NaN,NaN,10/24/2023,1200,,LO,13.5N,84.4W,20.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
df["Name"] = df["Name"].fillna(method='ffill')
df

C:\Users\saman\AppData\Local\Temp\ipykernel_29308\3213244409.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Name"] = df["Name"].fillna(method='ffill')

,Name,Num Entries,Year,Time,Record Identifier,Status of System,Latitude,Longitude,Maximum Sustained Wind,Minimum Pressure,...,34-knot Wind Radii SW,34-knot Wind Radii NW,50-knot Wind Radii NE,50-knot Wind Radii SE,50-knot Wind Radii SW,50-knot Wind Radii NW,64-knot Wind Radii NE,64-knot Wind Radii SE,64-knot Wind Radii SW,64-knot Wind Radii NW
0,UNNAMED,14,AL011851,UNNAMED,14,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,UNNAMED,NaN,1851-06-25,0000,,HU,28.0N,94.8W,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
2,UNNAMED,NaN,1851-06-25,0600,,HU,28.0N,95.4W,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
3,UNNAMED,NaN,1851-06-25,1200,,HU,28.0N,96.0W,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
4,UNNAMED,NaN,1851-06-25,1800,,HU,28.1N,96.5W,80.0,-999.0,...,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56717,TWENTY-ONE,NaN,10/23/2023,1800,,TD,11.5N,83.2W,25.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56718,TWENTY-ONE,NaN,10/24/2023,0000,,TD,12.2N,83.4W,25.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56719,TWENTY-ONE,NaN,10/24/2023,0130,L,TD,12.4N,83.5W,25.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56720,TWENTY-ONE,NaN,10/24/2023,0600,,TD,13.0N,83.8W,25.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56721,TWENTY-ONE,NaN,10/24/2023,1200,,LO,13.5N,84.4W,20.0,1007.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0